[package]
name = "ucftp_receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
hpke = { version = "0.13.0", default-features = false, features = ["x25519"] }
rand = "0.9.0"
ucftp_shared = { path = "../ucftp_shared" }
